### PR TITLE
Improved initialize_query: added possibility of passing scoped_model option in OverlapValidator

### PR DESCRIPTION
**Pull request by RutSzymon**
Hi, I've had problem with STI models.
I have Absence with PlannedAbsence and UnplannedAbsence subclasses, where they need to see each other during validation, so I passed Absence model as scope_model like this:
```
validates :start_date, :end_date, overlap: { scoped_model: "Absence" }
```
I hope you find this helpful.

If you have better idea to handle this, please let me know.

### CODE REVIEW

**Comment by robinbortlik** [comment]
Hi @RutSzymon , thank you for your PR. I really appreciate it. I'm very open to to this improvement. I would just change the implementation from 
```ruby 
options[:scoped_model].safe_constantize || record.class
``` 
to 
```ruby
options[:scoped_model].present? ? options[:scoped_model].constantize : record.class
```

The reason for that is that `safe_constantize` does not fail if I do a typo. Which is not wanted in this case. I want to developers be informed when they do something unintentional. Not silently use fallback. 

What do you think?

**Comment by RutSzymon** [comment]
Of course, you're right, your solution is better, thanks :)

**Comment by robinbortlik** [comment]
@RutSzymon why did you close PR? Was it intentionally?

**Comment by RutSzymon** [comment]
I'm sorry it was an accident

**Comment by robinbortlik** [comment]
@RutSzymon gem released, you can install ;)

**Comment by RutSzymon** [comment]
Thank you very much, best regards :)

**Pull request merged**
