### PR TITLE
allow to add error for multiple keys

### PR DESCRIPTION
**Pull request by rafaltrojanowski**

### CODE REVIEW

**Comment by robinbortlik** [comment]
Can you please add some example to readme? Thank you

**Comment by rafaltrojanowski** [comment]
Sure, I will update readme soon :)

**Comment by robinbortlik** [comment]
Ok.. then I will merge it.

**Comment by rafaltrojanowski** [comment]
Done

**Comment by robinbortlik** [comment]
Thank you very much for your work.

**Comment by rafaltrojanowski** [comment]
My pleasure, that's really useful stuff 👍

**Pull request merged**
